import Header from '@/components/ui/Header'
import Footer from '@/components/ui/Footer'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service | Sewa2u',
  description: 'Terms of service for Sewa2u.',
  alternates: { canonical: 'https://sewa2u.com/terms' },
  robots: { index: true, follow: true },
}

export default function TermsPage() {
  return (
    <div className="min-h-[100dvh] flex flex-col">
      <Header />
      <main className="flex-1 max-w-2xl mx-auto px-4 py-12">
        <h1 className="text-2xl font-bold text-navy-800 mb-6">Terms of Service</h1>
        <div className="space-y-6 text-navy-600 text-sm leading-relaxed">
          <p className="text-sm text-navy-400">Last updated: February 2026</p>

          <section>
            <h2 className="text-base font-semibold text-navy-800 mb-2">1. Service description</h2>
            <p>Sewa2u provides an online tool to generate Malaysia residential tenancy agreement documents. Documents are generated based on information you provide and are for reference purposes only.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-navy-800 mb-2">2. Not legal advice</h2>
            <p>Documents generated by Sewa2u are not legal advice. They are general templates that may not be suitable for all situations. You are strongly advised to consult a qualified lawyer before executing any tenancy agreement, especially for complex or high-value tenancies.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-navy-800 mb-2">3. Payment and refunds</h2>
            <p>PDF downloads are a one-time purchase (RM30 standard / RM55 custom). Due to the digital nature of the product, refunds are not available once the PDF has been downloaded. If you experience a technical issue preventing download after payment, contact us at <a href="mailto:whooshinglander@gmail.com" className="text-brand-600 hover:underline">whooshinglander@gmail.com</a> within 48 hours.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-navy-800 mb-2">4. Limitation of liability</h2>
            <p>Sewa2u and its operators are not liable for any loss, damage, or legal consequence arising from the use of documents generated by this service. Use at your own risk.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-navy-800 mb-2">5. Intellectual property</h2>
            <p>The Sewa2u website and its underlying software are proprietary. Generated PDF documents are licensed to you for personal use in connection with your tenancy.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-navy-800 mb-2">6. Governing law</h2>
            <p>These terms are governed by the laws of Malaysia.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-navy-800 mb-2">7. Contact</h2>
            <p>Questions? Email <a href="mailto:whooshinglander@gmail.com" className="text-brand-600 hover:underline">whooshinglander@gmail.com</a>.</p>
          </section>
        </div>
      </main>
      <Footer />
    </div>
  )
}
