// Generate sample PDFs for all property types
// Run: node scripts/generate-samples.mjs

import { writeFileSync } from 'fs'
import { execSync } from 'child_process'

// We need to use the Next.js build output, so let's hit the API directly
// But since the API needs to run in Next.js context, we'll create a standalone script

const samples = [
  {
    name: 'residential-Standard',
    tier: 'standard',
    formData: {
      propertyType: 'residential',
      propertyAddress: '45 Jalan Ampang, Kuala Lumpur',
      unitNumber: '#12-03',
      postalCode: '50450',
      landlordName: 'AHMAD BIN ISMAIL',
      landlordNric: '810101-01-1234',
      landlordAddress: '12 Jalan Sultan Ismail, Kuala Lumpur 50250',
      tenantName: 'MUHAMMAD FAIZ',
      tenantNric: '920202-02-5678',
      tenantEmail: 'john.smith@example.com',
      additionalTenants: [],
      commencementDate: '2026-04-01',
      expiryDate: '2028-03-31',
      monthlyRent: 2800,
      securityDeposit: 5600,
      handoverCondition: 'furnished',
      leaseRenewalOption: true,
      diplomaticClause: false,
      customClauses: ['AIRCON_TENANT', 'NO_SMOKING', 'MINOR_REPAIRS'],
      utilityCap: '',
      petDescription: '',
      freeTextClause: '',
      roomType: 'common',
      roomDescription: '',
      utilitiesIncluded: false,
      utilitiesSplitMethod: 'equal',
      utilitiesFixedAmount: '',
      wifiIncluded: false,
      sharedFacilities: [],
      houseRules: '',
      paymentBank: 'CIMB',
      paymentAccountName: 'AHMAD BIN ISMAIL',
      paymentAccountNo: '1234-567-8901',
      rentPaymentDay: 1,
      minorRepairThreshold: 150,
      diplomaticMinMonths: 12,
      diplomaticNoticeMonths: 2,
      renewalTermMonths: 12,
      purchaseNoticeMonths: 2,
      inventoryItems: [
        { name: 'Refrigerator (Samsung)', condition: 'good' },
        { name: 'Washing Machine (LG)', condition: 'good' },
        { name: 'Aircon x3 (Daikin)', condition: 'good' },
        { name: 'Queen Bed + Mattress (Master)', condition: 'fair' },
        { name: 'Dining Table + 4 Chairs', condition: 'good' },
      ],
      skipParties: false,
      skipTerms: false,
      skipProperty: false,
    }
  },
  {
    name: 'Private-Custom',
    tier: 'custom',
    formData: {
      propertyType: 'private',
      propertyAddress: '1 Mont Kiara, Kuala Lumpur',
      unitNumber: '#25-08',
      postalCode: '50480',
      landlordName: 'SITI NURHALIZA',
      landlordNric: '760303-03-9876',
      landlordAddress: '55 Jalan Ampang, Kuala Lumpur 50450',
      tenantName: 'LIM WEI MING',
      tenantNric: '850505-05-4321',
      tenantEmail: 'david.mueller@company.com',
      additionalTenants: [
        { name: 'SARAH MUELLER', nricPassport: 'E1234567X' }
      ],
      commencementDate: '2026-05-01',
      expiryDate: '2028-04-30',
      monthlyRent: 8500,
      securityDeposit: 17000,
      handoverCondition: 'furnished',
      leaseRenewalOption: true,
      diplomaticClause: true,
      customClauses: ['AIRCON_LANDLORD', 'NO_PETS', 'MINOR_REPAIRS', 'LANDLORD_ACCESS', 'ORIGINAL_CONDITION', 'VIEWING_CLAUSE'],
      utilityCap: '',
      petDescription: '',
      freeTextClause: 'The Landlord shall provide weekly pool maintenance at the Landlord\'s expense throughout the tenancy period.',
      roomType: 'common',
      roomDescription: '',
      utilitiesIncluded: false,
      utilitiesSplitMethod: 'equal',
      utilitiesFixedAmount: '',
      wifiIncluded: false,
      sharedFacilities: [],
      houseRules: '',
      paymentBank: 'Maybank',
      paymentAccountName: 'SITI NURHALIZA',
      paymentAccountNo: '5678-901-2345',
      rentPaymentDay: 1,
      minorRepairThreshold: 200,
      diplomaticMinMonths: 12,
      diplomaticNoticeMonths: 2,
      renewalTermMonths: 24,
      purchaseNoticeMonths: 2,
      inventoryItems: [
        { name: 'Smart TV 65" (Sony)', condition: 'good' },
        { name: 'Refrigerator (Bosch)', condition: 'good' },
        { name: 'Washer/Dryer (Miele)', condition: 'good' },
        { name: 'Aircon x4 (Mitsubishi)', condition: 'good' },
        { name: 'King Bed + Mattress (Master)', condition: 'good' },
        { name: 'Sofa Set (3+2 seater)', condition: 'good' },
        { name: 'Wine Chiller (Vintec)', condition: 'fair' },
      ],
      skipParties: false,
      skipTerms: false,
      skipProperty: false,
    }
  },
  {
    name: 'Room-Rental',
    tier: 'standard',
    formData: {
      propertyType: 'room',
      propertyAddress: '22 Jalan Gasing, Petaling Jaya',
      unitNumber: '#05-10',
      postalCode: '46200',
      landlordName: 'NUR AISYAH',
      landlordNric: '880707-07-5678',
      landlordAddress: '22 Jalan Gasing, Petaling Jaya 46200',
      tenantName: 'RAJESH KUMAR',
      tenantNric: '910808-08-9012',
      tenantEmail: 'maria.santos@email.com',
      additionalTenants: [],
      commencementDate: '2026-03-15',
      expiryDate: '2027-03-14',
      monthlyRent: 1100,
      securityDeposit: 1100,
      handoverCondition: 'furnished',
      leaseRenewalOption: false,
      diplomaticClause: false,
      customClauses: ['NO_SMOKING', 'NO_SUBLET'],
      utilityCap: '',
      petDescription: '',
      freeTextClause: '',
      roomType: 'common',
      roomDescription: 'Common room with built-in wardrobe, window facing east, ceiling fan and aircon.',
      utilitiesIncluded: false,
      utilitiesSplitMethod: 'equal',
      utilitiesFixedAmount: '',
      wifiIncluded: true,
      sharedFacilities: ['Kitchen', 'Living Room', 'Bathroom (shared)', 'Laundry Area'],
      houseRules: '1. No overnight guests without prior approval from Landlord.\n2. Quiet hours: 10PM to 8AM.\n3. Keep shared areas clean after use.\n4. No cooking of strong-smelling food without proper ventilation.\n5. Shoes to be left at the door.',
      paymentBank: 'Public Bank',
      paymentAccountName: 'NUR AISYAH',
      paymentAccountNo: '3456-789-0123',
      rentPaymentDay: 15,
      minorRepairThreshold: 100,
      diplomaticMinMonths: 12,
      diplomaticNoticeMonths: 2,
      renewalTermMonths: 12,
      purchaseNoticeMonths: 2,
      inventoryItems: [
        { name: 'Single Bed + Mattress', condition: 'good' },
        { name: 'Built-in Wardrobe', condition: 'good' },
        { name: 'Study Desk + Chair', condition: 'fair' },
        { name: 'Ceiling Fan', condition: 'good' },
        { name: 'Aircon (Daikin)', condition: 'good' },
      ],
      skipParties: false,
      skipTerms: false,
      skipProperty: false,
    }
  }
]

// Output as JSON for the API to consume
console.log(JSON.stringify(samples, null, 2))
